site_name: IES-3 Data Analysis Report
site_url: https://your-site-url
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - content.code.copy
    - content.action.edit
    - content.action.view
nav:
  - Home: index.md
  - Data Summary: data_summary.md
  - Exploratory Data Analysis: eda.md
  - Statistical Analysis: analysis.md
plugins:
  - search
  - charts
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
docs_dir: docs
site_dir: site